version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      frontend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      backend:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/clowarden-server"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: ["19-alpine3.19", "20-alpine3.19", "21-alpine3.19"]

  - package-ecosystem: "docker"
    directory: "/database/migrations"
    schedule:
      interval: "weekly"

