[workspace]
resolver = "2"
members = [
    "clowarden-cli",
    "clowarden-core",
    "clowarden-server"
]

[workspace.package]
version = "0.2.3"
license = "Apache-2.0"
edition = "2024"
rust-version = "1.96.1"

[workspace.dependencies]
anyhow = "1.0.103"
as-any = "0.3.2"
askama = "0.16.0"
async-trait = "0.1.89"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
bytes = "1.12.0"
cached = { version = "2.0.2", features = ["async"] }
clap = { version = "4.6.1", features = ["derive"] }
clowarden-core = { path = "../clowarden-core" }
deadpool-postgres = { version = "0.14.1", features = ["serde"] }
figment = { version = "0.10.19", features = ["yaml", "env"] }
futures = "0.3.32"
hmac = "0.13.0"
hex = "0.4.3"
mime = "0.3.17"
mockall = "0.15.0"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
openssl = { version = "0.10.81", features = ["vendored"] }
pem = "3.0.6"
postgres-openssl = "0.5.3"
regex = "1.12.4"
reqwest = { version = "0.11.14", default-features = false, features = [
    "json",
    "multipart",
] } # do-not-upgrade
reqwest-conditional-middleware = "0.1.0" # do-not-upgrade
reqwest-middleware = "0.1.5" # do-not-upgrade
reqwest-retry = "0.1.4" # do-not-upgrade
reqwest-tracing = "0.3.0" # do-not-upgrade
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_qs = "1.1.2"
serde_yaml = "0.9.34"
sha2 = "0.11.0"
thiserror = "2.0.18"
time = { version = "0.3.53", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.52.3", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-postgres = { version = "0.7.18", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tokio-util = { version = "0.7.18", features = ["rt"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["auth", "fs", "set-header", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.23.4", features = ["serde", "v4"] }
