[workspace]
members = [
    "clowarden-cli",
    "clowarden-core",
    "clowarden-server"
]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
anyhow = "1.0.71"
askama = "0.12.0"
async-trait = "0.1.68"
axum = { version = "0.6.18", features = ["macros"] }
base64 = "0.21.2"
cached = "0.44.0"
clap = { version = "4.3.9", features = ["derive"] }
clowarden-core = { path = "../clowarden-core" }
config = "0.13.3"
deadpool-postgres = { version = "0.10.5", features = ["serde"] }
futures = "0.3.28"
hmac = "0.12.1"
hex = "0.4.3"
lazy_static = "1.4.0"
mime = "0.3.17"
mockall = "0.11.4"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
openssl = { version = "0.10.55", features = ["vendored"] }
pem = "2.0.1"
postgres-openssl = "0.5.0"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
serde_qs = "0.12.0"
serde_yaml = "0.9.22"
sha2 = "0.10.7"
thiserror = "1.0.40"
time = { version = "0.3.22", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.29.0", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-postgres = { version = "0.7.8", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["auth", "fs", "set-header", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
uuid = { version = "1.4.0", features = ["serde", "v4"] }
