[workspace]
members = [
    "clowarden-cli",
    "clowarden-core",
    "clowarden-server"
]

[workspace.package]
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
anyhow = "1.0.75"
askama = "0.12.0"
async-trait = "0.1.73"
axum = { version = "0.6.20", features = ["macros"] }
base64 = "0.21.2"
cached = "0.44.0"
clap = { version = "4.3.24", features = ["derive"] }
clowarden-core = { path = "../clowarden-core" }
config = "0.13.3"
deadpool-postgres = { version = "0.10.5", features = ["serde"] }
futures = "0.3.28"
hmac = "0.12.1"
hex = "0.4.3"
lazy_static = "1.4.0"
mime = "0.3.17"
mockall = "0.11.4"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
openssl = { version = "0.10.56", features = ["vendored"] }
pem = "3.0.2"
postgres-openssl = "0.5.0"
regex = "1.9.3"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
serde_qs = "0.12.0"
serde_yaml = "0.9.25"
sha2 = "0.10.7"
thiserror = "1.0.47"
time = { version = "0.3.27", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.32.0", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-postgres = { version = "0.7.9", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["auth", "fs", "set-header", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
uuid = { version = "1.4.1", features = ["serde", "v4"] }
