[workspace]
resolver = "2"
members = [
    "clowarden-cli",
    "clowarden-core",
    "clowarden-server"
]

[workspace.package]
version = "0.1.1"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
anyhow = "1.0.86"
as-any = "0.3.1"
askama = "0.12.1"
async-trait = "0.1.80"
axum = { version = "0.7.5", features = ["macros"] }
base64 = "0.22.1"
cached = { version = "0.51.4", features = ["async"] }
clap = { version = "4.5.7", features = ["derive"] }
clowarden-core = { path = "../clowarden-core" }
config = "0.13.4"
deadpool-postgres = { version = "0.14.0", features = ["serde"] }
futures = "0.3.30"
hmac = "0.12.1"
hex = "0.4.3"
lazy_static = "1.5.0"
mime = "0.3.17"
mockall = "0.12.1"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
openssl = { version = "0.10.64", features = ["vendored"] }
pem = "3.0.4"
postgres-openssl = "0.5.0"
regex = "1.10.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
serde_qs = "0.13.0"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
thiserror = "1.0.61"
time = { version = "0.3.36", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.38.0", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-postgres = { version = "0.7.10", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["auth", "fs", "set-header", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
uuid = { version = "1.9.1", features = ["serde", "v4"] }
