[package]
name = "clowarden"
description = "CLOWarden"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.67"

[dependencies]
anyhow = "1.0.70"
askama = "0.12.0"
async-trait = "0.1.68"
axum = { version = "0.6.15", features = ["macros"] }
base64 = "0.21.0"
cached = "0.43.0"
clap = { version = "4.2.2", features = ["derive"] }
config = "0.13.3"
deadpool-postgres = { version = "0.10.5", features = ["serde"] }
futures = "0.3.28"
hmac = "0.12.1"
hex = "0.4.3"
lazy_static = "1.4.0"
mime = "0.3.17"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
openssl = { version = "0.10.50", features = ["vendored"] }
pem = "2.0.1"
postgres-openssl = "0.5.0"
regex = "1.7.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_qs = "0.12.0"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
thiserror = "1.0.40"
time = { version = "0.3.20", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.27.0", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-postgres = { version = "=0.7.7", features = [
    "with-uuid-1",
    "with-serde_json-1",
    "with-time-0_3",
] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["auth", "fs", "set-header", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }
uuid = { version = "1.3.1", features = ["serde", "v4"] }

[dev-dependencies]
mockall = "0.11.4"
