apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}server-config
type: Opaque
stringData:
  clowarden.yml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    log:
      format: {{ .Values.log.format }}
    server:
      addr: {{ .Values.server.addr }}
      staticPath: {{ .Values.server.staticPath }}
      basicAuth:
        enabled: {{ .Values.server.basicAuth.enabled }}
        username: {{ .Values.server.basicAuth.username }}
        password: {{ .Values.server.basicAuth.password }}
      githubApp:
        appId: {{ .Values.server.githubApp.appId }}
        privateKey: {{ .Values.server.githubApp.privateKey | quote }}
        webhookSecret: {{ .Values.server.githubApp.webhookSecret | quote }}
    services:
      github:
        enabled: {{ .Values.services.github.enabled }}
    organizations: {{ toYaml .Values.organizations | nindent 6 }}

