apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}server-config
type: Opaque
stringData:
  clowarden.yml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    log:
      format: {{ .Values.log.format }}
    server:
      addr: {{ .Values.server.addr }}
      staticPath: {{ .Values.server.staticPath }}
      basicAuth:
        enabled: {{ .Values.server.basicAuth.enabled }}
        username: {{ .Values.server.basicAuth.username }}
        password: {{ .Values.server.basicAuth.password }}
      githubApp:
        appId: {{ .Values.server.githubApp.appId }}
        installationId: {{ .Values.server.githubApp.installationId }}
        privateKey: {{ .Values.server.githubApp.privateKey | quote }}
        webhookSecret: {{ .Values.server.githubApp.webhookSecret | quote }}
      config:
        organization: {{ .Values.server.config.organization }}
        repository: {{ .Values.server.config.repository }}
        branch: {{ .Values.server.config.branch }}
        legacy:
          enabled: {{ .Values.server.config.legacy.enabled }}
          sheriff:
            permissionsPath: {{ .Values.server.config.legacy.sheriff.permissionsPath }}
          {{- with .Values.server.config.legacy.cncf.peoplePath }}
          cncf:
            peoplePath: {{ . }}
          {{- end }}
        services:
          github:
            enabled: {{ .Values.server.config.services.github.enabled }}
