apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}server
  labels:
    app.kubernetes.io/component: server
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $serviceType := default "ClusterIP" .Values.server.service.type }}
  {{- if eq $serviceType "LoadBalancer" }}
  allocateLoadBalancerNodePorts: {{ .Values.server.service.allocateLoadBalancerNodePorts }}
  {{- end }}
  type: {{ $serviceType }}
  ports:
    {{- toYaml .Values.server.service.ports | nindent 4 }}
  selector:
    app.kubernetes.io/component: server
    {{- include "chart.selectorLabels" . | nindent 4 }}
