apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}clowarden
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}job-reader
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}clowarden-job-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "chart.resourceNamePrefix" . }}clowarden
roleRef:
  kind: Role
  name: {{ include "chart.resourceNamePrefix" . }}job-reader
  apiGroup: rbac.authorization.k8s.io
