apiVersion: v2
name: clowarden
description: CLOWarden is a tool that manages access to resources across multiple services
type: application
version: 0.2.3
appVersion: 0.2.3
kubeVersion: ">= 1.19.0-0"
home: https://clowarden.io
icon: https://raw.githubusercontent.com/cncf/clowarden/main/docs/logo/logo.png
keywords:
  - clowarden
maintainers:
  - name: Sergio
    email: tegioz@icloud.com
  - name: Cintia
    email: cynthiasg@icloud.com
dependencies:
  - name: postgresql
    version: 18.0.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/category: skip-prediction
  artifacthub.io/changes: |
    - kind: changed
      description: Cache GitHub clients and retry failed requests
    - kind: changed
      description: Some refactoring in Helm chart
    - kind: changed
      description: Update Helm chart's readme file
    - kind: changed
      description: Upgrade frontend dependencies
  artifacthub.io/images: |
    - name: dbmigrator
      image: ghcr.io/cncf/clowarden/dbmigrator:v0.2.3
    - name: server
      image: ghcr.io/cncf/clowarden/server:v0.2.3
  artifacthub.io/links: |
    - name: source
      url: https://github.com/cncf/clowarden
    - name: support
      url: https://github.com/cncf/clowarden/issues
